apiVersion: cagip.cagip.github.com/v2
kind: Project
metadata:
  labels:
    app.kubernetes.io/name: jfrog-operator
    app.kubernetes.io/managed-by: kustomize
  name: project-sample
spec:
  # TODO(user): Add fields here
